---
# khulnasoft - Declarative CLI Version Manager
# https://khulnasoftproj.github.io/
registries:
  - type: standard
    ref: v4.40.0 # renovate: depName=khulnasoftproj/khulnasoft-registry
packages:
  - name: cli/cli@v2.32.1
