---
name: Check files
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/check-files.yaml
      - pkgs/**/pkg.yaml
      - pkgs/**/registry.yaml
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/check-files.yaml
      - pkgs/**/pkg.yaml
      - pkgs/**/registry.yaml
jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: khulnasoftproj/registry-action/check-files@v0.2.0
